language: cpp

compiler:
  - g++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc-4.8
    - g++-4.8
    - libboost1.55-all-dev
    - cmake

before_install:
  - export NUM_CPU="`grep processor /proc/cpuinfo | wc -l`"; echo $NUM_CPU

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8 -std=c++11 -pthread" CC="gcc-4.8"; fi

env:
  - BUILD_DIR="."
  - BUILD_DIR="test"

before_script:
  - cd $BUILD_DIR
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j$NUM_CPU
  - if [ -e "test" ]; then ./test; fi

notifications:
  email:
    on_failure: always