######################################################################
# Automatically generated by qmake (3.0) Fri Jul 3 11:25:06 2015
######################################################################
TEMPLATE = app
TARGET = traff_sim
CONFIG += c++11
LIBS += -lpthread 

INCLUDEPATH += .

SOURCES += \
    main.cpp

HEADERS += \
    inc/stdafx.hpp
